vim.g.mapleader = " "
vim.opt.autowrite = true
vim.opt.clipboard = "unnamedplus"
vim.opt.confirm = true
vim.opt.cursorline = true
vim.opt.fillchars = { foldopen = "", foldclose = "", fold = " ", foldsep = " ", eob = " " }
vim.opt.foldcolumn = "1"
vim.opt.foldlevel = 99
vim.opt.foldnestmax = 1
vim.opt.foldtext = ""
vim.opt.laststatus = 3
vim.opt.linebreak = true
vim.opt.list = true
vim.opt.number = true
vim.opt.pumblend = 10
vim.opt.pumheight = 10
vim.opt.relativenumber = true
vim.opt.shiftround = true
vim.opt.shiftwidth = 0
vim.opt.showmode = false
vim.opt.signcolumn = "yes"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.tabstop = 2
vim.opt.title = true
vim.opt.titlestring = "nvim[%{fnamemodify(getcwd(), ':t')}]"
vim.opt.undofile = true
vim.opt.virtualedit = "block"
