vim.g.mapleader = " "
vim.opt.clipboard = "unnamedplus"
vim.opt.cursorline = true
vim.opt.foldenable = false
vim.opt.foldnestmax = 1
vim.opt.list = true
vim.opt.mouse = ""
vim.opt.number = true
vim.opt.showmode = false
vim.opt.swapfile = false
vim.opt.tabstop = 4
vim.opt.timeoutlen = 300
vim.opt.undofile = true
vim.opt.updatetime = 250
